package model;


// Generated 07/05/2018 20:44:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Flashcard generated by hbm2java
 */
public class Flashcard  implements java.io.Serializable {


     private Integer codigo;
     private Pasta pasta;
     private Usuario usuario;
     private String pergunta;
     private String resposta;
     private String nivel;
     private String titulo;
     private boolean publico;
     private Set<Assunto> assuntos = new HashSet<Assunto>(0);

    public Flashcard() {
    }

	
    public Flashcard(Usuario usuario, String pergunta, String resposta, String nivel, String titulo, boolean publico) {
        this.usuario = usuario;
        this.pergunta = pergunta;
        this.resposta = resposta;
        this.nivel = nivel;
        this.titulo = titulo;
        this.publico = publico;
    }
    public Flashcard(Pasta pasta, Usuario usuario, String pergunta, String resposta, String nivel, String titulo, boolean publico, Set<Assunto> assuntos) {
       this.pasta = pasta;
       this.usuario = usuario;
       this.pergunta = pergunta;
       this.resposta = resposta;
       this.nivel = nivel;
       this.titulo = titulo;
       this.publico = publico;
       this.assuntos = assuntos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Pasta getPasta() {
        return this.pasta;
    }
    
    public void setPasta(Pasta pasta) {
        this.pasta = pasta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getPergunta() {
        return this.pergunta;
    }
    
    public void setPergunta(String pergunta) {
        this.pergunta = pergunta;
    }
    public String getResposta() {
        return this.resposta;
    }
    
    public void setResposta(String resposta) {
        this.resposta = resposta;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public boolean isPublico() {
        return this.publico;
    }
    
    public void setPublico(boolean publico) {
        this.publico = publico;
    }
    public Set<Assunto> getAssuntos() {
        return this.assuntos;
    }
    
    public void setAssuntos(Set<Assunto> assuntos) {
        this.assuntos = assuntos;
    }




}


